name: ci
# This workflow is triggered on pushes to the repository.
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    # Job name is Greeting
    name: build
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: '16.x'
      - run: yarn install
      - name: Run linter
        uses: ./
        with:
          working-directory: aptossnap/
          lint: yarn lint
      - name: Build
        run: yarn run build