name: ci
# This workflow is triggered on pushes to the repository.
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    # Job name is Greeting
    name: build
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          cache: yarn
          node-version: '16.x'
      - run: yarn install --immutable
      - name: Run linter
        run: yarn run lint
      - name: Build
        run: yarn run build
      - uses: tj-actions/verify-changed-files@v9
        id: verify-changed-files
        with:
          files: |
             packages/snap/snap.manifest.json
